# Generated by Django 5.1.1 on 2024-11-03 13:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True)),
                ('password_reset_token', models.CharField(blank=True, max_length=36, null=True)),
                ('is_reset_password_possible', models.BooleanField(default=False)),
                ('password_reset_token_created_at', models.DateTimeField(blank=True, null=True)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_default', models.BooleanField(default=False)),
                ('privileged', models.BooleanField(default=False)),
                ('color', models.CharField(default='#FFFFFF', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('website', models.URLField(blank=True, null=True)),
                ('confirmation_code', models.CharField(blank=True, max_length=6, null=True)),
                ('confirmation_code_created_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Domainactivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('Débutant', 'BEGINNER'), ('Intermédiaire', 'INTERMEDIATE'), ('Avancé', 'ADVANCED'), ('Courant', 'FLUENT'), ('Natif', 'NATIVE')], max_length=20)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('gender', models.CharField(blank=True, choices=[('Homme', 'MALE'), ('Femme', 'FEMALE')], max_length=10, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('wilaya', models.CharField(blank=True, max_length=100, null=True)),
                ('daira', models.CharField(blank=True, max_length=100, null=True)),
                ('confirmation_code', models.CharField(blank=True, max_length=36, null=True)),
                ('confirmation_code_created_at', models.DateTimeField(blank=True, null=True)),
                ('birth_date', models.DateField()),
                ('wished_salary', models.PositiveIntegerField(blank=True, null=True)),
                ('military_service', models.BooleanField(default=False)),
                ('married', models.BooleanField(default=False)),
                ('driving_license', models.BooleanField(default=False)),
                ('owns_vehicle', models.BooleanField(default=False)),
                ('is_passport_valid', models.BooleanField(default=False)),
                ('current_situation', models.CharField(blank=True, choices=[('En Fin de Contrat', 'CONTRACT_END'), ('En Poste', 'EMPLOYED'), ('Sans Emploi', 'UNEMPLOYED')], max_length=20, null=True)),
                ('is_immediate_available', models.BooleanField(default=True)),
                ('mobility', models.CharField(choices=[('Régional', 'REGIONAL'), ('National', 'NATIONAL'), ('International', 'INTERNATIONAL')], default='Régional', max_length=20)),
                ('study_level', models.CharField(blank=True, max_length=30, null=True)),
                ('domainactivity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.domainactivity')),
                ('profession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.profession')),
                ('skills', models.ManyToManyField(blank=True, related_name='employes', to='api.skill')),
            ],
            options={
                'verbose_name': 'Employe',
                'verbose_name_plural': 'Employes',
            },
            bases=('api.profile',),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('Email', 'Email'), ('Phone', 'Phone')], max_length=100)),
                ('info', models.CharField(max_length=60, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='api.company')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('job_level', models.CharField(choices=[('Débutant / junior', 'BEGINNER_JUNIOR'), ('Responsable équipe', 'TEAM_LEADER'), ('Cadre dirigeant', 'EXECUTIVE'), ('Stagiaire étudiant', 'INTERN_STUDENT'), ('Manager / responsable departement', 'MANAGER_DEPARTMENT_HEAD'), ('Confirme experimente', 'CONFIRMED_EXPERIENCED'), ('Jeune diplome', 'RECENT_GRADUATE'), ('Test', 'TEST')], max_length=100)),
                ('contract_type', models.CharField(choices=[('CDI', 'Indefinite_term'), ('CDD', 'Fixed_term'), ('Mission', 'Mission')], max_length=100)),
                ('diplome', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField()),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
                ('available_spots', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('salary', models.PositiveIntegerField(blank=True, null=True)),
                ('wilaya', models.CharField(blank=True, max_length=100, null=True)),
                ('daira', models.CharField(blank=True, max_length=100, null=True)),
                ('localisation', models.URLField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='api.company')),
                ('domain_activity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='offers', to='api.domainactivity')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='offers', to='api.profession')),
                ('skills', models.ManyToManyField(blank=True, related_name='offers', to='api.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Qualifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='api.offer')),
            ],
        ),
        migrations.CreateModel(
            name='Responsibilitie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsibilities', to='api.offer')),
            ],
        ),
        migrations.CreateModel(
            name='SocialCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Socials', to='api.company')),
                ('social', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.social')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_admin', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_admins', to='api.company')),
            ],
            options={
                'verbose_name': 'CompanyUser',
                'verbose_name_plural': 'CompanyUsers',
            },
            bases=('api.profile',),
        ),
        migrations.CreateModel(
            name='SavedOfferEmploye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved', to='api.offer')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_offers', to='api.employe')),
            ],
        ),
        migrations.CreateModel(
            name='OfferEmploye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='api.offer')),
                ('status', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='api.applicationstatus')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied', to='api.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='api.employe')),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
            },
        ),
        migrations.CreateModel(
            name='EmployeLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.language')),
                ('employe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='api.employe')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeHobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hobby')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hobbies', to='api.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Diplome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=100)),
                ('establishment', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplomes', to='api.employe')),
            ],
            options={
                'verbose_name': 'diplome',
                'verbose_name_plural': 'diplomes',
            },
        ),
    ]
