# Generated by Django 5.1.1 on 2024-11-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_offeremploye_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='excel_files/')),
            ],
        ),
    ]
